
源程序对应的汇编代码如下:

DATA		SEGMENT
	h DB   ' h ' ,0DH ,0AH,'$'
	a DD ?
	u DD ?
	i DD ?
	b DD ?
	c DD ?
	d DD ?
DATA		ENDS
CODE		SEGMENT
		ASSUME CS:CODE,DS:DATA
BEGIN:		MOV AX,DATA
		MOV DS,AX
		MOV AL,         '
		MOV TEMP_DB_1,AL
		MOV AL,TEMP_DB_1
		MOV h AL
		MOV EAX,        10
		MOV TEMP_DD_1,EAX
		MOV EAX,TEMP_DD_1
		MOV a EAX
		MOV EAX,        10
		MOV TEMP_DD_2,EAX
		MOV EAX,TEMP_DB_2
		MUL EAX,-1
		MOV TEMP_DD_1 EAX
		MOV EAX,TEMP_DD_1
		MOV u EAX
		MOV EAX,a
		MOV TEMP_DD_1,EAX
		MOV EAX,        10
		MOV TEMP_DD_2,EAX
      MOV EAX TEMP_DD_1
      CMP EAX TEMP_DD_2
         JELABEL_0
        MOV TEMP_DD_1,0
        JMP LABEL_1
LABEL_0:
        MOV TEMP_DD_1,1
LABEL_1:
		MOV AL,TEMP_DB_1
		CMP AL,0
		JLE LABEL_2
		MOV EAX,         1
		MOV TEMP_DD_3,EAX
		MOV EAX,TEMP_DD_3
		MOV a EAX
LABEL_2:
		MOV EAX,         0
		MOV TEMP_DD_3,EAX
		MOV EAX,TEMP_DD_3
		MOV i EAX
		LABEL_3:
		MOV EAX,i
		MOV TEMP_DD_3,EAX
		MOV EAX,         9
		MOV TEMP_DD_4,EAX
      MOV EAX TEMP_DD_3
      CMP EAX TEMP_DD_4
         JLLABEL_4
        MOV TEMP_DD_1,0
        JMP LABEL_5
LABEL_4:
        MOV TEMP_DD_1,1
LABEL_5:
		MOV AL,TEMP_DB_1
		CMP AL,0
		JLE LABEL_6
		MOV EAX,TEMP_DD_5
		MOV a EAX
		MOV EAX,TEMP_DD_5
		MOV a EAX
		MOV EAX,i
		MOV TEMP_DD_6,EAX
		MOV EAX,TEMP_DD_6
		ADD EAX,         1
		MOV TEMP_DB_5 EAX
		MOV EAX,TEMP_DD_5
		MOV i EAX
		JMP LABEL_3
LABEL_6:
LABEL_7:
		MOV EAX,a
		MOV TEMP_DD_5,EAX
		MOV EAX,         1
		MOV TEMP_DD_6,EAX
      MOV EAX TEMP_DD_5
      CMP EAX TEMP_DD_6
         JELABEL_8
        MOV TEMP_DD_1,0
        JMP LABEL_9
LABEL_8:
        MOV TEMP_DD_1,1
LABEL_9:
		MOV AL,TEMP_DB_1
		CMP AL,0
		JLE LABEL_10
		MOV EAX,a
		MOV TEMP_DD_8,EAX
		MOV EAX,TEMP_DD_8
		ADD EAX,        10
		MOV TEMP_DB_7 EAX
		MOV EAX,TEMP_DD_7
		MOV a EAX
		MOV EAX,a
		MOV TEMP_DD_7,EAX
		MOV EAX,TEMP_DD_7
		MOV b EAX
		MOV EAX,a
		MOV TEMP_DD_7,EAX
		MOV EAX,        11
		MOV TEMP_DD_8,EAX
      MOV EAX TEMP_DD_7
      CMP EAX TEMP_DD_8
         JELABEL_11
        MOV TEMP_DD_1,0
        JMP LABEL_12
LABEL_11:
        MOV TEMP_DD_1,1
LABEL_12:
		MOV AL,TEMP_DB_1
		CMP AL,0
		JLE LABEL_13
		MOV EAX,a
		MOV TEMP_DD_10,EAX
		MOV EAX,TEMP_DD_10
		MOV EBX,       100
		MUL EBX
		MOV TEMP_DD_9 EAX
		MOV EAX,TEMP_DD_9
		MOV c EAX
		JMP 1415
LABEL_13:
		MOV EAX,a
		MOV TEMP_DD_10,EAX
		MOV EAX,TEMP_DD_10
		MOV EBX,b
		MUL EBX
		MOV TEMP_DD_9 EAX
		MOV EAX,TEMP_DD_9
		MOV d EAX
LABEL_14:
		JMP LABEL_7
LABEL_10:
		MOV EAX,a
		MOV TEMP_DD_10,EAX
		MOV EAX,TEMP_DD_10
		MOV BX,         2
		DIV BX
		MOV TEMP_DD_9 EAH
		MOV EAX,TEMP_DD_9
		MOV a EAX
		MOV EAX,a
		MOV TEMP_DD_10,EAX
		MOV EAX,TEMP_DD_10
		ADD EAX,         3
		MOV TEMP_DB_9 EAX
		MOV EAX,TEMP_DD_9
		MOV b EAX
          MOVE AX,4CH
          INT 21H
CODE		ENDS
		END BEGIN
